FROM node:10-jessie-slim
WORKDIR /app

ENV MONGODB_URI

COPY package.json .

COPY . .
COPY .env packages/server/.env

RUN yarn global add typescript@3.4.2

RUN yarn install
RUN cd packages/server && sh -c tsc

CMD ["node", "./packages/server/build/index.js"]
