FROM node:10-jessie-slim
WORKDIR /app

COPY package.json .

COPY . .
COPY .env packages/server/.env

RUN yarn global add forever typescript@3.4.2

RUN yarn install
RUN cd packages/server && sh -c tsc

CMD forever start ./packages/server/build/index.js
