FROM node:10-jessie-slim
WORKDIR /app

COPY package.json .

COPY . .
COPY .env packages/app/.env

RUN yarn install
RUN cd packages/server && yarn tsc

RUN yarn global add forever

CMD forever start ./packages/server/build/index.js
